Add Predis support
md-systems/redis pull request #25
Opened 2017-09-12 03:42 UTC by leonardosul

I have added Predis as a composer dependency for the module, and added in some necessary classes to make it work. Since Predis and PhpRedis support essentially all of the same Redis functions underneath, and most of them are named the same everything works out of the box.

There are also some updates to the existing tests, and and ENV variable set to allow testing both Predis and PhpRedis with TravisCI.

2017-09-12 22:44 UTC, Berdir requested changes
Very nice work, lets do a few more of those suggested cleanups and then we can get this in.

2017-09-12 22:44 UTC, Berdir commented on README.Predis.txt
> +$settings['cache']['bins']['bootstrap'] = 'cache.backend.chainedfast';
this is no longer necessary and can be removed.

2017-09-12 22:44 UTC, Berdir commented on composer.json
> +  "require": {
maybe make this a recommends instead of require, because if you use the extension, you don't want to be forced to install predis?

2017-09-12 22:44 UTC, Berdir commented on src/Cache/Predis.php
> +  protected $checksumProvider;
maybe we can move a few more things to the base class, e.g. shared properties

2017-09-12 22:44 UTC, Berdir commented on src/Cache/Predis.php
> +  public function getMultiple(&$cids, $allow_invalid = FALSE) {
quite a lot of the code is duplicated obviously. But refactoring things would make this much bigger, so maybe we could do that in a follow-up, e.g. in this case, I could imagine a doGetMultiple() method and the stuff above/below is then exactly the same.

2017-09-12 22:44 UTC, Berdir commented on src/Cache/Predis.php
> +  protected function createEntryHash($cid, $data, $expire = Cache::PERMANENT, array $tags) {
I guess at least this and the expand method should be identical between the two backends, so it should be fairly easy to move them into the base class here?

2017-09-12 22:44 UTC, Berdir commented on tests/src/Functional/Lock/RedisLockFunctionalTest.php
> +    $redis_interface = getenv('REDIS_INTERFACE');
nice, great to see that this is working so well. Maybe we should have a default or at least throw a clear exception if this value is not set. I see there are a few setup methods, we could possibly make that a simple trait and throw the exception there, the trait could maybe just return the value in one method and another that sets the settings.

2017-09-13 11:07 UTC, leonardosul commented
Hey mate, I have made the suggested changes. Tests are passing again. Would be great to get this merged to the dev branch.

2017-09-13 22:55 UTC, leonardosul commented on src/Cache/Predis.php
> +  public function getMultiple(&$cids, $allow_invalid = FALSE) {
getMultiple is slightly different for Predis as the multi function behaves differently. I had to use pipeline instead. All other common functions have been moved to the base class.

2017-09-14 06:25 UTC, Berdir commented
Great. Had to doublecheck that you're indeed https://www.drupal.org/u/maniosullivan, different usernames are confusing :)

Squashing and merging this now.

2017-09-14 06:25 UTC, closed without merging